### PR TITLE
#167: Style.scss imports a file that does not exist in recent versions of react-flexview (closes #167)

### LINKED ISSUE #167: Style.scss imports a file that does not exist in recent versions of react-flexview
In `style.scss` there is the following import:
```
@import '~react-flexview/lib/flexView.css';
```

but that file does not exist anymore since `react-flexview` 4.0.0

### PR DESCRIPTION
**Pull request by zanza00**
Closes [#2521117](https://buildo.kaiten.io/space/[object Object]/card/2521117)

⚠️ The line above was added during the automatic migration of all github project issues to Kaiten. The old GH issue link is kept here for reference (it is now deprecated, continue follow the original issue on Kaiten).

Closes #167

I had to fix the `min-height` of the cells for dates, months and years

### tests performed

`npm start`

image

image

### tests not performed (domain coverage)

> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.

### CODE REVIEW

**Review by giogonzo — CHANGES_REQUESTED** [review]
I would avoid adding the `package-lock.json` file.

Also, looking at the screenshots, the height of some cells (the selected ones) looks a bit off (see the white border at the bottom)

**Comment by zanza00** [comment]
removed lock file and fixed current cell box size (I updated the screenshots)

**Review by giogonzo — COMMENTED** [review]
looks much better!

Still I'm seeing something a bit off (horizontally now, the year cell overflows to the left a few pixels)

I would also review this live with @alessandravilla (since we don't have a preview here)

**Comment by zanza00** [comment]
Toghether with @FrancescoCioria we did some pairing and we decided to remove the border of the selected cell since it was causing all sorts of problem.

**Review by FrancescoCioria — APPROVED** [review]

**Review by alessandravilla — APPROVED** [review]

**Pull request merged**
